sonar.projectKey=Les-Chauffagistes_coins-service
sonar.projectName=Coins service
sonar.organization=les-chauffagistes

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.13

sonar.cpd.exclusions=tests/**