sonar.projectKey=Les-Chauffagistes_coins-service
sonar.projectName=Coins service
sonar.organization=les-chauffagistes

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.cpd.exclusions=tests/**